export default {
  index: {
    title: "Visão geral",
    theme: { toc: false },
  },
  "configurador-3d": "Configurador 3D",
  materiais: "Materiais",
  "portas-e-gavetas": "Portas e Gavetas",
  "lista-de-corte": "Lista de Corte",
  "nesting-fast-pro": "Nesting Fast/PRO",
  "exportacao-tcn-drill-xml": "Exportação TCN/Drill XML",
  "exportacao-cnc-tcn-drill-xml": {
    title: "Exportação TCN/Drill XML (antigo)",
    display: "hidden",
  },
  "pdf-tecnico": "PDF técnico",
  orcamentos: "Orçamentos",
  "pimo-trak": "PIMO-TRAK",
  "modulo-industrial": "Módulo Industrial",
  ferragens: "Ferragens",
  definicoes: "Definições",
  "conta-e-acesso": "Conta e acesso",
  "modo-foto": "Modo foto",
  "sala-e-ambiente": "Sala e ambiente",
  remates: "Remates",
  "relatorio-final": "Relatório final",
  "analise-projetos": "Análise de projetos",
  "estacoes-industriais": "Estações industriais",
}
