export default {
  "automacao-fabrico": "Automação no fabrico de mobiliário: do projeto à linha de produção",
  "bem-vindo": "Bem-vindo ao blog PIMO",
  "comercio-mundial-moveis": "Comércio mundial de mobiliário: crescimento moderado e novos equilíbrios",
  "contraplacado-aglomerado": "Contraplacado e aglomerado: como escolher o painel certo",
  "cozinhas-planeadas": "Cozinhas planeadas: do levantamento à montagem com projeto coerente",
  "exportacao-cnc-ficheiros": "Exportação CNC: TCN e Drill XML na prática",
  "fabrico-digital-2026": "Fabrico digital em 2026: tendências qualitativas para a madeira",
  "ferragens-hettich": "Ferragens Hettich no projeto de mobiliário: sistemas que o PIMO ajuda a especificar",
  "furacao-industrial": "Furação industrial no mobiliário: da peça ao ficheiro para a máquina",
  "ia-carpintaria": "Inteligência artificial na carpintaria e no desenho de mobiliário",
  "lista-corte-residuos": "Lista de corte e gestão de resíduos: do projeto à chapa com menos desperdício",
  "madeiras-macicas": "Madeiras maciças no mobiliário: espécies, estabilidade e projeto digital",
  "materiais-cozinhas": "Materiais de cozinha: durabilidade na carcaça e nas frentes",
  "mdf-guia-pratico": "MDF: guia prático para carpintaria e mobiliário",
  "melamina-paineis": "Melamina e painéis decorativos: escolher, cortar e orçamentar com rigor",
  "nesting-cnc": "Nesting CNC: optimizar chapas, reduzir desperdício e ligar ao projeto",
  "orlagem-bordos": "Orlagem de bordos: acabamento, precisão e ligação ao projeto digital",
  "pimo-trak-rastreio": "PIMO TRAK: rastrear peças da exportação à montagem",
  "portas-gavetas-fabrico": "Regras de fabrico para portas e gavetas",
  "profissao-carpinteiro": "A profissão de carpinteiro em 2026: oficina, digital e mobiliário sob medida",
  "software-design-3d": "Software de design 3D para marcenaria: o que procurar e como o PIMO se encaixa",
  "sustentabilidade-madeira": "Sustentabilidade na madeira e no mobiliário: certificação, resíduos e escolhas de projeto",
}
